#!/usr/bin/env bash
# Configures an Ubuntu server with localhost resolving to 127.0.0.2 and facebook.com to 8.8.8.8
cp /etc/hosts /etc/hosts.bak
grep -v 'localhost\|facebook.com' /etc/hosts.bak > /etc/hosts
echo '127.0.0.2 localhost' >> /etc/hosts
echo '8.8.8.8 facebook.com' >> /etc/hosts
